import React from "react";

export default function Skills() {
  return (
    <div>
      <section id="resume">
        <div>
          <p id="gear">⚙️</p>
        </div>
        <div className="resume">
          <div className="skills">
            <div className="frontend">
              <ul>
                <li>
                  <img
                    alt="react"
                    src="https://img.shields.io/badge/-
                    React-navy?style=flat&logo=react"
                  ></img>
                </li>
                <li>
                  <img
                    alt="CSS"
                    src="https://img.shields.io/badge/-CSS-navy?style=flat&logo=css3&logoColor=red"
                  ></img>
                </li>
                <li>
                  <img
                    alt="Bootstrap"
                    src="https://img.shields.io/badge/-Bootstrap-navy?style=flat&logo=bootstrap&logoColor=turquoise"
                  ></img>
                </li>
                <li>
                  <img
                    alt="HTML5"
                    src="https://img.shields.io/badge/-HTML5-navy?style=flat&logo=HTML5&logoColor=brightgreen"
                  ></img>
                </li>
                <li>
                  <img
                    alt="Handlebars"
                    src="https://img.shields.io/badge/-Handlebars-navy?style=flat&logo=handlebars.js&logoColor=orange"
                  ></img>
                </li>
                <li>
                  <img
                    alt="IndexedDB"
                    src="https://img.shields.io/badge/-IndexedDB-navy?style=flat&logo=bookstack&logoColor=gold"
                  ></img>
                </li>
                <li>
                  <img
                    alt="GraphQL"
                    src="https://img.shields.io/badge/-GraphQL-navy?style=flat&logo=graphql&logoColor=magenta"
                  ></img>
                </li>
                <li>
                  <img
                    alt="Thymeleaf"
                    src="https://img.shields.io/badge/-Thymeleaf-navy?style=flat&logo=Thymeleaf"
                  ></img>
                </li>
                <li>
                  <img
                    alt="JavaScript"
                    src="https://img.shields.io/badge/-JavaScript-navy?style=flat&logo=javascript"
                  ></img>
                </li>
              </ul>
            </div>
            <div className="backend">
              <ul>
                <li>
                  <img
                    alt="MySQL"
                    src="https://img.shields.io/badge/-MySQL-navy?style=flat&logo=mysql&logoColor=white"
                  ></img>
                </li>
                <li>
                  <img
                    alt="Sequelize"
                    src="https://img.shields.io/badge/-Sequelize-navy?style=flat&logo=sequelize&logoColor=white"
                  ></img>
                </li>
                <li>
                  <img
                    alt="MongoDB"
                    src="https://img.shields.io/badge/-MongoDB-navy?style=flat&logo=MongoDB&logoColor=brightgreen"
                  ></img>
                </li>
                <li>
                  <img
                    alt="Mongoose"
                    src="https://img.shields.io/badge/-Mongoose-navy?style=flat&logo=MongoDB&logoColor=turquoise"
                  ></img>
                </li>
                <li>
                  <img
                    alt="Express"
                    src="https://img.shields.io/badge/-Express-navy?style=flat&logo=express"
                  ></img>
                </li>
                <li>
                  <img
                    alt="DynamoDB"
                    src="https://img.shields.io/badge/-DynamoDB-navy?style=flat&logo=Amazon&logoColor=orange"
                  ></img>
                </li>
                <li>
                  <img
                    alt="GraphQL"
                    src="https://img.shields.io/badge/-GraphQL-navy?style=flat&logo=graphql&logoColor=magenta"
                  ></img>
                </li>
                <li>
                  <img
                    alt="Node"
                    src="https://img.shields.io/badge/-Node-navy?style=flat&logo=node.js&logoColor=yellow"
                  ></img>
                </li>
                <li>
                  <img
                    alt="JAVA"
                    src="https://img.shields.io/badge/-JAVA Spring-navy?style=flat&logo=Spring"
                  ></img>
                </li>
                <li>
                  <img
                    alt="Python"
                    src="https://img.shields.io/badge/-Python-navy?style=flat&logo=Python&logoColor=yellow"
                  ></img>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      
    </div>
  );
}
